Implemented Design for Orientation Pages
projecthuman-repo/Coquest-WebApp pull request #51
Opened 2024-05-23 23:43 UTC by mariiadevphc

2024-05-24 15:54 UTC, nick-cd requested changes

2024-05-24 15:54 UTC, nick-cd commented on frontend/src/pages/Orientation/Pages/Bio.tsx
> +    const [location, setLocation] = useState(props.user?.location);
Do you plan to use the user's location for something?

2024-05-24 21:01 UTC, christian-phc commented on frontend/src/pages/Orientation/Pages/RelativeLocation.tsx
> -            {/* TODO: Find out how to place a space in the middle of the postal code mask without introducing inconsistencies */}
Must have overlooked this. Fix can be found on commit [ee9e367](https://github.com/projecthuman-repo/Coquest-WebApp/pull/51/commits/ee9e3672b9e69743a7cc79d1448f7003904891c1). Now it visually adds the space for the user and should show the same results as the ones pre-fix.

2024-05-24 21:40 UTC, christian-phc commented on frontend/src/pages/Orientation/Pages/Bio.tsx
> +                <h3 className="main-heading">Welcome to Coquest&#44; {props.user?.name}!</h3>
Removed break tags in favor of margin. Changes on [a036b03](https://github.com/projecthuman-repo/Coquest-WebApp/pull/51/commits/a036b039ad50a36c41142b88514a207770d7a684).

2024-05-26 11:58 UTC, nick-cd commented on frontend/src/pages/Orientation/Pages/RelativeLocation.tsx
> -            {/* TODO: Find out how to place a space in the middle of the postal code mask without introducing inconsistencies */}
My apologies. Yes, you are correct. I glossed over some details when reviewing on my phone 😅

2024-05-26 12:05 UTC, nick-cd commented on frontend/src/pages/Orientation/Pages/Bio.tsx
> +                <h3 className="main-heading">Welcome to Coquest&#44; {props.user?.name}!</h3>
Thanks!

I see some straggling break tags in `Orientation.tsx`. May you remove those as well?

2024-05-28 20:03 UTC, mariiadevphc commented on frontend/src/components/UploadImage/Cropper.tsx
> +const CROP_WIDTH = 175;
Changed for consistency. When the user generates an image its dimensions is 175px by 175px, so just to make it consistent and nice, the image's display dimensions are set to be the same.

2024-05-28 20:05 UTC, mariiadevphc commented on frontend/src/pages/Orientation/Pages/Bio.tsx
> +    const [location, setLocation] = useState(props.user?.location);
Location was implemented on this page before I saw that there's a separate page for it, forgot to remove, thanks for noticing :) Removed now.

2024-05-28 20:05 UTC, mariiadevphc commented on frontend/src/pages/Orientation/Orientation.tsx
> +                {/* TODO: would make sense to add a progress bar to show progress in onboarding completion */}
Implemented with 849a8b5275ec52e33eb78ecbf932e8cd965249b2

2024-05-28 20:06 UTC, mariiadevphc commented on frontend/src/pages/Orientation/Pages/Bio.tsx
> +                <h3 className="main-heading">Welcome to Coquest&#44; {props.user?.name}!</h3>
Removed with 849a8b5275ec52e33eb78ecbf932e8cd965249b2

2024-05-28 21:44 UTC, nick-cd commented on frontend/src/components/UploadImage/Cropper.tsx
> +const CROP_WIDTH = 175;
Makes sense, thanks!

2024-05-28 22:08 UTC, merged