Implement dropdown menu in Toolbar and various UI improvements
projecthuman-repo/Coquest-WebApp pull request #54
Opened 2024-05-29 15:22 UTC by joey-PHC-dev

- Added DropdownMenu component to the Toolbar.
- Implemented a profile dropdown menu with links to Wallet, Inventory, Tickets, and Settings.
- Styled the dropdown menu to match the provided design, including icons and hover effects.
- Fixed alignment and spacing issues in the Toolbar.
- Added hover effect for the profile icon in the Toolbar.
- Adjusted the spacing between the Profile Name and the View Profile link in the dropdown menu.
- Included temporary page reload workaround for navigation on Notification and Message icons click in the Toolbar.
- Improved the positioning and styling of the dropdown menu to ensure it is displayed correctly below the profile icon.

2024-06-01 08:51 UTC, nick-cd requested changes

2024-06-01 08:51 UTC, nick-cd commented on frontend/src/components/Profile/UserProfileExternal.tsx
> +                if (user.id === userId) {
If I understand the logic correctly, I think we should raise this condition to the parent component. This way, we can make sure the external profile component _only_ renders when ID is some other co-quest user.

2024-06-01 08:51 UTC, nick-cd commented on frontend/src/components/Profile/UserProfileInternal.tsx
> +        const setupSubscription = async () => {
I also suggest raising the current user subscription to the parent component and pass the user down as a prop. It'll clean up the child components.

2024-06-03 13:21 UTC, joey-PHC-dev commented on frontend/src/components/Profile/UserProfileExternal.tsx
> +                if (user.id === userId) {
Moved user data subscription logic from UserProfileInternal and UserProfileExternal to UserProfile component

2024-06-03 13:21 UTC, joey-PHC-dev commented on frontend/src/components/Profile/UserProfileInternal.tsx
> +        const setupSubscription = async () => {
Updated UserProfileInternal to receive user data as a prop and refactored the component accordingly

2024-06-03 13:27 UTC, merged