Feature/posts (Posts, navbar issue fix and logout)
projecthuman-repo/Coquest-WebApp pull request #89
Opened 2024-07-20 02:34 UTC by mariiadevphc

- Post Feed (`/posts`)
- Create Post form to add post to Post Feed (`/posts/create`)
- Fixed Navbar issue (navbar didn't appear after login, had to refresh)
- Logout - click on your name in navbar for menu to appear, and Logout will be part of the options (`/logout`)

2024-07-21 12:38 UTC, nick-cd requested changes
Thank you for your hard work here!

Can you quickly add an empty `alt` atribute to your decorative images? Once you do, I'll merge!

2024-07-21 12:38 UTC, nick-cd commented on frontend/src/pages/Orientation/Pages/RelativeLocation.tsx
> +				<img src="/icons/location.png" className="location-icon" />
```suggestion
				<img src="/icons/location.png" alt="" className="location-icon" />
```

2024-07-21 12:38 UTC, nick-cd commented on frontend/src/pages/Orientation/Pages/Interests.tsx
> +					src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png"
```suggestion
					src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png"
alt=""
```

2024-07-22 03:43 UTC, mariiadevphc commented on frontend/src/pages/Orientation/Pages/Interests.tsx
> +					src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-512.png"
fixed with 61fc7db1aa0500c49dfe22fc232b880df2fcbb01

2024-07-22 03:43 UTC, mariiadevphc commented on frontend/src/pages/Orientation/Pages/RelativeLocation.tsx
> +				<img src="/icons/location.png" className="location-icon" />
fixed with 61fc7db1aa0500c49dfe22fc232b880df2fcbb01

2024-07-22 19:26 UTC, nick-cd approved these changes

2024-07-22 19:30 UTC, merged